# TODO: Use `pnp` when commitlint & nuxt3 & supports it
# @see https://github.com/conventional-changelog/commitlint/issues/2637
# @see https://github.com/nuxt/framework/issues/5411
# @see https://yarnpkg.com/configuration/yarnrc#nodeLinker
nodeLinker: node-modules
# plugins:
#   - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
#     spec: "@yarnpkg/plugin-workspace-tools"
